### PR TITLE
Added bind to Seq

### PR DESCRIPTION
**Pull request by paucarre**

### CODE REVIEW

**Comment by dbrattli** [comment]
Thanks for the PR. Bind is called `collect` in this library. Is there any difference between the two?

**Comment by paucarre** [comment]
@dbrattli oh, I didn't expect `collect` to do that.

`bind` to me is the functional `flat_map` . I see that `option` and other types use `bind` as `flat_map`, which is the monad method. To me it is very confusion that the monad method is called `bind` for some types and `collect` for others.
Specifically, a Monad `flat_map`/`bind` should have the following signature:
```
    def bind(self, mapper: Callable[[TSource], Monad[TResult]]) -> Monad[TResult]:
```
As Python doesn't have support for higher kinded types, you have to implement that for each type. But I would say, having different names for the same "logic" causes confusion more than anything.

`collect` to me has potentially other meanings like the ones in [Akka streams](https://doc.akka.io/docs/akka/current/stream/stream-cookbook.html)

**Comment by dbrattli** [comment]
I agree that this can be confusing. The `seq` module is ported from the F# [`Seq` module](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-seqmodule.html#collect) where it called `collect`. Can you perhaps change your PR to add `bind` as an alias for `collect` (or the other way around)? I see they have added this alias to e.g [FSharpPlus](https://fsprojects.github.io/FSharpPlus/reference/fsharpplus-seq.html#bind), so we're not the only one that thinks this can be confusing.

**Comment by paucarre** [comment]
@dbrattli I can add bind as alias for collect, is that ok for you?

**Comment by paucarre** [comment]
@dbrattli 
I added `bind` as an alias to `collect` but I also did a few changes, which I can revert if you tell me what you want.
These changes are types in inputs and outputs. The inputs I used superclass ( `Iterable` instead of `Seq`) so that they are more "useful" (they span more cases). On the other hand, for the outputs I used the subclasses (`Seq` instead of `Iterable`) so that they are, again, more "useful", spanning more use-cases. 
This is related to covariance and contravariance of types in methods. I can revert back if you want.

**Comment by dbrattli** [comment]
@paucarre Thanks, this is very nice. For `bind` it's great to have the mapper return `Iterable`. But for `seq` as a module the idea is that the pure functions only works on `Iterable` (no wrap /unwrap, so should not return Seq as a class).

**Comment by dbrattli** [comment]
PS: Also seq testing usually need to `list` the result before you can compare since iterables are lazy.

**Comment by paucarre** [comment]
> PS: Also seq testing usually need to `list` the result before you can compare since iterables are lazy.

Yep, that's already there with lists to load all the contents

**Comment by paucarre** [comment]
@dbrattli is that good to go now or are there anything left to change?

**Comment by dbrattli** [comment]
@paucarre Run tests locally with `pytest` fix any issues and commit. You also might want to run `pre-commit run --all-files` before submitting to make sure it builds and passes all checks. The branch is also out-of-date with main, so please merge main or rebase.

**Comment by dbrattli** [comment]
Closed because of inactivity

**Pull request closed without merging**
